export enum REGION {
    NORTH_VIETNAM = 'NORTH_VIETNAM',
    MIDDLE_VIETNAM = 'MIDDLE_VIETNAM',
    SOUTH_VIETNAM = 'SOUTH_VIETNAM',
    HA_NOI = 'HA_NOI',
    HO_CHI_MINH = 'HO_CHI_MINH',
    CAN_THO = 'CAN_THO',
    KIEN_GIANG = 'KIEN_GIANG',
    TIEN_GIANG = 'TIEN_GIANG',
    BAC_NINH = 'BAC_NINH',
    QUANG_NGAI = 'QUANG_NGAI',
}
