export enum MBTI_ANSWER {
    TOTAL_AGREE = 'TOTAL_AGREE',
    QUITE_AGREE = 'QUITE_AGREE',
    AGREE = 'AGREE',
    NEUTRAL = 'NEUTRAL',
    DISAGREE = 'DISAGREE',
    QUITE_DISAGREE = 'QUITE_DISAGREE',
    TOTAL_DISAGREE = 'TOTAL_DISAGREE',
}

export const mbtiAnswers = [
    MBTI_ANSWER.TOTAL_AGREE,
    MBTI_ANSWER.QUITE_AGREE,
    MBTI_ANSWER.AGREE,
    MBTI_ANSWER.NEUTRAL,
    MBTI_ANSWER.DISAGREE,
    MBTI_ANSWER.QUITE_DISAGREE,
    MBTI_ANSWER.TOTAL_DISAGREE,
];
