export enum TYPE_IMAGE {
    ORIGINAL = 'ORIGINAL',
    RESIZED = 'RESIZED',
    SQUARE = 'SQUARE',
    BLUR = 'BLUR',
    BLUR_RESIZED = 'BLUR_RESIZED',
    BLUR_SQUARE = 'BLUR_SQUARE',
    BLUR_PIXELATE = 'BLUR_PIXELATE',
}
